import type { Metadata } from "next";
import "./globals.css";
import { NavOption } from "./types/types";
import MainHeader from "./components/header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const options:NavOption[] = [
    { name: "Inicio", url: "/"},
    { name: "Explorar", url: "explorar"},
    { name: "Perfil", url: "perfil"}
  ]
  return (
    <html lang="en">
      <body>
        <MainHeader options={options}></MainHeader>
        {children}
      </body>
    </html>
  );
}
